export const ROUTER_PATH = {
  ROOT: "/",
  MAIN: "/",
  ADD: "/add",
  CLIP: "/clip",
  CLIP_DETAIL: "/clip/[id]",
  CLIP_SEARCH: "/clip/search",
  LOGIN: "/login",
  SIGN_UP: "/signup",
  SEARCH: "/search",
  FRIEND_SEARCH: "/friend/search",
  FRIEND_SHARED: "/friend/shared",
  SETTING: "/setting",
  SUMMARY: "/summary",
};
